apiVersion: v1
kind: PersistentVolume
metadata:
   name: test-vllm-pv
   labels:
      model: "llama"

spec:
   capacity:
      storage: 50Gi
   accessModes:
      - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
   storageClassName: standard
   hostPath:
      path: /home/ubuntu/test-vllm-storage